@startuml
'https://plantuml.com/sequence-diagram

autonumber
'
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

CreateCollection -> DepositManager: createDeposit
DepositManager -> FileService: assertDiskSpace
CreateCollection <- DepositManager: Deposit details
CreateCollection -> DepositManager: Add payload to deposit
CreateCollection <-- DepositManager: Deposit details
CreateCollection -> DepositManager: If inProgress is false, finalizeDeposit

@enduml
