@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

class DepositEntry {
depositId: String
filename: String
mimeType: String
hash: String
packaging: String
contentLength: long
}

class Deposit {
id: String
entries: DepositEntry[]
inProgress: boolean
}

Deposit *-- DepositEntry
DepositHandler *-- DepositReceiptFactory
DepositHandler *-- DepositStatementFactory

interface DepositHandler {
+ createDeposit()
+ getDeposit(depositId)
+ addPayload(depositId, entry: DepositEntry, inProgress, inputStream)
}

interface DepositReceiptFactory {
+ createDepositReceipt(depositId)
}

class DepositReceiptFactoryImpl {
- depositHandler: DepositHandler
}

DepositReceiptFactory <|-- DepositReceiptFactoryImpl

interface DepositStatementFactory {
+ createDepositStatement(depositId)
}

class DepositStatementFactoryImpl {
- depositHandler: DepositHandler
}

DepositStatementFactory <|-- DepositStatementFactoryImpl

@enduml
