@startuml
'https://plantuml.com/sequence-diagram

autonumber
'
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

DepositManager -> DepositProperties: set state to UPLOADED
DepositManager -> DepositProperties: in another thread, set state to FINALIZING
DepositManager -> BagExtractor: extract bag (either single or multiple files)
BagExtractor -> ZipService: extract bag into specific path
ZipService -> FileService: if multiple files, merge them
ZipService <- FileService: path to merged file
ZipService -> ZipService: unzip file
BagExtractor <- ZipService: path to unzipped file (first folder)
DepositManager -> DepositProperties: set state to SUBMITTED
DepositManager -> FileService: remove zip files
DepositManager -> DepositProperties: remove content type property
DepositManager -> FileService: move folder to final destination
@enduml
